### ISSUE TITLE
Indentation dans la fonction ImportStatblock

### ISSUE THREAD

**Issue by stephaned68** [Ulty/ChroniquesGalactiques#6]
Salut @Ulty 

Je ne sais pas ce qui s’est passé quand j’ai copié collé mais l’indentation est à l’ouest dans la première fonction d’import de pnj. Ça n’empeche pas le fonctionnement, mais si tu peux passer ça dans un beautify quelconque avant de soumettre dans le git officiel, ça ne serait pas plus mal.

Merci d’avance !

**Comment by Ulty** [comment]
Ok, je m'en occupe.

**Comment by Ulty** [comment]
@stephaned68 : Tu as fait un super boulot, bravo !
